### ISSUE TITLE
求教如何使用weex-analyzer-ios

### ISSUE THREAD

**Issue by songxing10000** [weexteam/weex-analyzer-ios#2]

**Comment by xiayun200825** [comment]
1. 引入`WeexAnalyzer.h`
2. 开启Debug模式 `[WeexAnalyzer enableDebugMode];`
3. 在创建WeexInstance时，绑定到WeexAnalyzer `[WeexAnalyzer bindWXInstance:wxInstance];`
4. WeexInstance销毁时，解除绑定 `[WeexAnalyzer unbindWXInstance];`

**Comment by songxing10000** [comment]
收到谢谢，周一去公司试试
